spring:
  jpa:
    generate-ddl: true

management:
  open-telemetry:
    resource-attributes:
      spring.instance.id: value1sasfafs
  wavefront:
    uri: https://telegraf.hub-collector.service.internal:8765
    application:
      name: spring-music-e2e
      service-name: spring-music-db
      custom-tags:
        instance_guid: ${CF_INSTANCE_GUID}
  info:
    #    build-timestamp: @maven.build.timestamp@
    git:
      enabled: true
      mode: full
    env:
      enabled: true
    java:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    info:
      show-values: ALWAYS
      git:
        mode: full
    beans:
      enabled: true
    conditions:
      enabled: true
    configprops:
      enabled: true
      show-values: ALWAYS
    env:
      show-values: ALWAYS
    loggers:
      enabled: true
    mappings:
      enabled: true
    probes:
      enabled: true
    health:
      enabled: true
      show-details: ALWAYS

#logging:
#  level:
#    ROOT: DEBUG
---
spring:
  config:
    activate:
      on-profile: http2

server:
  http2:
    enabled: true

#---
#spring:
#  config:
#    activate:
#      on-profile: mysql
#  datasource:
#    url: "jdbc:postgresql://q-s0.postgres-instance.rare-1232661-services-subnet.service-instance-d6b14617-194c-48c2-9355-0bd1b0f54460.bosh:5432/postgres?user=pgadmin&password=30OZdSrPC497TF186X52/music"
#    driver-class-name: com.mysql.jdbc.Driver
#    username: pgadmin
#    password: 30OZdSrPC497TF186X52
#  jpa:
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.MySQL55Dialect

#---
#spring:
#  config:
#    activate:
#      on-profile: postgres
#  datasource:
#    url: "jdbc:postgresql://q-s0.postgres-instance.rare-1232661-services-subnet.service-instance-d6b14617-194c-48c2-9355-0bd1b0f54460.bosh:5432/postgres?user=pgadmin&password=30OZdSrPC497TF186X52/music"
#    driver-class-name: org.postgresql.Driver
#    username: pgadmin
#    password: 30OZdSrPC497TF186X52
#  jpa:
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.ProgressDialect
